import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { supabase } from './lib/supabase';
import { BrandLogo } from './components/BrandLogo';
import './pro-login.css';

const loginSchema=z.object({email:z.string().email('Enter a valid email address'),password:z.string().min(6,'Use at least 6 characters')});
type LoginValues=z.infer<typeof loginSchema>;

export function ProLogin(){const nav=useNavigate();const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<LoginValues>({resolver:zodResolver(loginSchema)});const [error,setError]=useState('');return <main className="pro-login"><section className="login-story"><Link to="/" className="login-brand"><BrandLogo/></Link><div className="story-copy"><p className="eyebrow">WELCOME BACK</p><h1>Your next confident answer is <em>waiting.</em></h1><p>Continue building the interview skills that turn preparation into momentum.</p></div><div className="story-quote"><span>“</span><p>The feedback showed me exactly how to turn a good answer into a great one.</p><div><b>CareerPilot learner</b><small>Frontend developer track</small></div></div><div className="story-orb story-orb-one"/><div className="story-orb story-orb-two"/></section><section className="login-form-wrap"><Link to="/" className="login-mobile-brand"><BrandLogo/></Link><div className="login-form-card"><div className="form-heading"><p className="eyebrow">YOUR PRACTICE SPACE</p><h2>Sign in to CareerPilot</h2><p>Pick up right where your progress left off.</p></div><form onSubmit={handleSubmit(async values=>{setError('');if(!supabase){setError('Authentication is not configured yet.');return}const result=await supabase.auth.signInWithPassword(values);if(result.error){setError(result.error.message);return}nav('/dashboard')})}><label>Email address<input {...register('email')} type="email" autoComplete="email" placeholder="you@example.com"/></label>{errors.email&&<small className="field-error">{errors.email.message}</small>}<label>Password<input {...register('password')} type="password" autoComplete="current-password" placeholder="Enter your password"/></label>{errors.password&&<small className="field-error">{errors.password.message}</small>}<div className="login-options"><label className="remember"><input type="checkbox"/> <span>Keep me signed in</span></label><a href="mailto:support@careerpilot.ai?subject=Password%20help">Forgot password?</a></div>{error&&<p className="login-error">{error}</p>}<button className="login-submit" disabled={isSubmitting}>{isSubmitting?'Signing you in…':'Continue to my dashboard'} <span>→</span></button></form><p className="new-account">New to CareerPilot? <Link to="/register">Create your free account</Link></p><div className="login-safe"><span>✦</span> Your interview practice and feedback stay private.</div></div></section></main>}
