import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { supabase } from './lib/supabase';
import { BrandLogo } from './components/BrandLogo';
import './pro-register.css';

const registerSchema=z.object({email:z.string().email('Enter a valid email address'),password:z.string().min(6,'Use at least 6 characters')});
type RegisterValues=z.infer<typeof registerSchema>;
export function ProRegister(){const nav=useNavigate();const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<RegisterValues>({resolver:zodResolver(registerSchema)});const [error,setError]=useState('');const [sent,setSent]=useState(false);return <main className="pro-register"><section className="register-form-wrap"><Link to="/" className="register-brand"><BrandLogo/></Link><div className="register-card"><p className="eyebrow">YOUR NEXT CHAPTER</p><h1>Build interview confidence, one answer at a time.</h1><p className="register-intro">Start your free practice space. It takes less than a minute.</p>{sent?<div className="confirm-card"><span>✓</span><h2>Check your inbox</h2><p>We sent a confirmation link to your email. Once confirmed, return here and sign in to begin.</p><Link className="register-submit" to="/login">Go to sign in <b>→</b></Link></div>:<form onSubmit={handleSubmit(async values=>{setError('');if(!supabase){setError('Authentication is not configured yet.');return}const result=await supabase.auth.signUp(values);if(result.error){setError(result.error.message);return}if(result.data.session)nav('/onboarding');else setSent(true)})}><label>Email address<input {...register('email')} type="email" autoComplete="email" placeholder="you@example.com"/></label>{errors.email&&<small className="field-error">{errors.email.message}</small>}<label>Create a password<input {...register('password')} type="password" autoComplete="new-password" placeholder="At least 6 characters"/></label>{errors.password&&<small className="field-error">{errors.password.message}</small>}{error&&<p className="login-error">{error}</p>}<button className="register-submit" disabled={isSubmitting}>{isSubmitting?'Creating your space…':'Create my free account'} <b>→</b></button></form>}<p className="register-signin">Already have an account? <Link to="/login">Sign in instead</Link></p><p className="register-terms">By continuing, you agree to use CareerPilot for learning and practice—not hiring decisions.</p></div></section><section className="register-showcase"><div className="showcase-grid"/><div className="showcase-content"><p className="eyebrow">WHAT YOU GET</p><h2>A calm place to<br/><em>get better.</em></h2><ul><li><span>✦</span><div><b>Role-specific practice</b><small>Questions built for your target role and level.</small></div></li><li><span>✦</span><div><b>Feedback that explains why</b><small>Go beyond scores with clear, useful coaching.</small></div></li><li><span>✦</span><div><b>A focused weekly plan</b><small>Know exactly what to practice next.</small></div></li></ul></div><div className="register-mini-card"><span>YOUR FIRST WIN</span><b>One thoughtful answer<br/>is a strong start.</b><i>→</i></div></section></main>}
